spring:
  application:
    name: zuul

server:
  port: 8080

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}