server:
   port: 0

spring:
  application:
    name: acme-payment
  datasource:
    url: jdbc:postgresql://localhost:5432/acme-payment
    username: postgres
    password: postgres
    initialization-mode: always
    separator: ^^^ END OF SCRIPT ^^^
  jpa:
    generate-ddl: off
    ddl-auto: validate
    show-sql: on
    open-in-view: false
    properties:
      hibernate.default_schema: public
  jackson:
    serialization:
      INDENT_OUTPUT: true
      FAIL_ON_EMPTY_BEANS: false

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR